### PR TITLE
Update diagrams-core.cabal

### PR DESCRIPTION
**Pull request by vaibhavsagar**
Bump upper bound for lens dependency.

### CODE REVIEW

**Comment by kostmo** [comment]
Hi, I didn't see your PR before I opened #98.  What are your thoughts on whether the major or minor version of the `lens` bound should be bumped?

**Comment by vaibhavsagar** [comment]
I think a minor version bump is less controversial and more likely to get merged, and a major version bump might possibly lead to a situation where the newest `lens` breaks something in `diagrams`, but otherwise I have no preference. My real goal is to see the `diagrams-*` packages back in the current LTS :smile:.

**Comment by byorgey** [comment]
Thanks for all the PRs --- sorry we've been dragging our feet on updating diagrams for the latest `lens`.  I've been working hard on an ICFP submission, but next week the ICFP submission will be done and it will be spring break, so I will definitely get everything updated then!

**Comment by kostmo** [comment]
Hi, any update on ETA?

**Comment by byorgey** [comment]
Working on it... apologies for the long wait! I have had a lot on my plate this semester.

**Comment by vaibhavsagar** [comment]
Thanks!

**Comment by kostmo** [comment]
Will there be a new version uploaded to [Hackage](https://hackage.haskell.org/package/diagrams-core) as well?

**Comment by byorgey** [comment]
Yes, there will.  At the moment I am trying to get it building on travis-ci.org again, so I can make sure that support for older GHCs still works.

**Comment by byorgey** [comment]
I've now released `diagrams-core-1.4.1` to Hackage which builds with GHC 8.4 and `lens-4.16`.  I'm continuing to work on similar updates to other diagrams packages.

**Comment by vaibhavsagar** [comment]
Thank you! This will make it easier to use with IHaskell :smile:

**Pull request merged**
