### PR TITLE
Pre 1.3

### PR DESCRIPTION
**Pull request by cchalmers**
See diagrams/diagrams-lib#241.

### CODE REVIEW

**Comment by byorgey** [comment]
I took a careful look through the changes and this all looks good to me.  Though I fully support renaming `(|>)` so as not to conflict with lens, I can't say I'm a huge fan of `(>|)`.  What about `(.>>)`?  So it's reminiscent of `(.>)` which takes a name on the left and the right, whereas `(.>>)` would take a name on the left and something more complicated (potentially something full of lots of names) on the right.

**Comment by bergey** [comment]
Why remove `instance Wrapped Name`?

Other than that and the naming decision, LGTM.  Thanks for splitting this up; it makes it much easier for me to understand & review.

**Comment by cchalmers** [comment]
Using `(.>>)` sounds good to me. It overlaps with function from `Biapply` from `bifunctors` but no one uses it :)

I'm not sure why I removed the `Wrapped` instance. I'll add it again.

**Comment by cchalmers** [comment]
> Thanks for splitting this up; it makes it much easier for me to understand & review.

I've recently discovered `git rebase -i` so I can make all my PRs pretty :)

**Pull request merged**
